baseURL = ""
languageCode = "en-us"
title = "My New Hugo Site"
disableKinds = ["taxonomy", "taxonomyTerm"]

[frontmatter]
    date = ["date","publishDate", "lastmod"]
    lastmod = ["lastmod", "date","publishDate"]


[params]
    appname = "Rightpoint Design System"
    appshortname = "RPDS"
    appthemecolor = "#ffffff"
    appbackgroundcolor = "#ffffff"
    msapptilecolor = "#da532c"
    mqsmall = "360px"
    mqmedium = "640px"
    mqlarge = "960px"
    mqextralarge = "1440px"

# [taxonomies]
#   category = ""
#   tag = ""

# [mediaTypes]
#     [mediaTypes."text/webmanifest"]
#         suffixes = ["webmanifest"]

# [outputFormats]
#     [outputFormats.webmanifest]
#         baseName = "site"
#         isPlainText = true
#         mediaType = "text/webmanifest"

# [outputs]
#     home = ["HTML","WEBMANIFEST"]



